### ISSUE TITLE
Hash button being weird?

### ISSUE THREAD

**Issue by ergpopler** [pop-os/popsicle#116] opened 2020-12-04 20:57 UTC
(appimage from release page)When i click on the hash button to select the type, it acts weird and acts like a double click? Holding down to select works, idk if thats what it's supposed to do though.

Video:
https://ufile.io/443rl23y

**Comment by ids1024** [comment] 2020-12-10 21:18
Looking at the video, I see what you mean. Strange though, I haven't seen it behave like that. The dropdown is just a [`GtkComboBoxText`](https://developer.gnome.org/gtk3/stable/GtkComboBoxText.html) so I can't think of any reason it would differ from other Gtk software. You don't see this issue in any other programs?

(I think I've seen something like that before in other programs, but with a mouse or keyboard issue causing input events that shouldn't happen and broke plenty more.)

**Comment by ids1024** [comment] 2020-12-10 21:27
Oh, and specifically trying with the AppImage from https://github.com/pop-os/popsicle/releases/tag/1.3.0 on Pop!_OS 20.10, I still can't reproduce, and it behaves like a normal dropdown.

**Comment by ids1024** [comment] 2021-01-04 18:08
Closing since this hasn't been reproduced by anyone else, and it should just work the same as any other `GtkComboBox`. Not sure what the problem is but it doesn't seem to be an issue in Popsicle.

This can be reopened if someone else sees a similar issue, or there more information about the problem.

**Closed by ids1024** 2021-01-04 18:08 UTC
