### ISSUE TITLE
Can't create bootable usb for Windows .iso

### ISSUE THREAD

**Issue by github2099** [pop-os/popsicle#161] opened 2021-09-01 06:29 UTC
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by leviport** [comment] 2021-09-01 15:06
Not much context here, but if you mean what I think you mean, then making Windows isos bootable is still in the works. 

Duplicate of https://github.com/pop-os/popsicle/issues/67

**Closed by leviport** 2021-09-01 15:06 UTC
