### ISSUE TITLE
Windows 10 Install

### ISSUE THREAD

**Issue by thomas992** [pop-os/popsicle#181] opened 2022-05-09 09:02 UTC
Pop_OS! 22.04 the popsicle application does not install Windows 10. Popsicle leads to the galp3 getting a "press any key to boot from DVD.." followed by a return. Restoring image with gnome disks does not work, when Windows 10 installation starts it says can not locate media drivers. I suspect it is the file system.

The installation ISO is over 4 gigabytes now, meaning that one has to be able to format it to the exFAT file system. Trying to do this without lollipop I tried
sudo add-apt-repository universe
sudo apt-install exfat-fuse
Open the Gnome Disks application, format your USB to exFAT.

I read online that I could copy and paste the ISO into the USB now but that does not work for me. I also tried Ventoy2Disk which I found interesting with it's Web interface but it does not format.

**Comment by leviport** [comment] 2023-07-21 17:58
I believe this is a duplicate of https://github.com/pop-os/popsicle/issues/67

**Closed by leviport** 2023-07-21 17:58 UTC
